name: Compile JAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: |
          ./gradlew shadowJar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Source
          path: ./build/libs/ManoCraft.jar
